CREATE TABLE AcessoSistema (
  idAcessoSistema INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Setor_idSetor INTEGER UNSIGNED NOT NULL,
  Nome VARCHAR(20) NOT NULL,
  IdSetor INTEGER UNSIGNED NOT NULL,
  Telefone INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idAcessoSistema),
  INDEX AcessoSistema_FKIndex1(Setor_idSetor)
);

CREATE TABLE Demandas (
  idDemandas INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Pedido_idPedido INTEGER UNSIGNED NOT NULL,
  Logradouro INTEGER UNSIGNED NOT NULL,
  Numero INTEGER UNSIGNED NOT NULL,
  Complemento INTEGER UNSIGNED NOT NULL,
  Bairro INTEGER UNSIGNED NOT NULL,
  Descricao INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idDemandas),
  INDEX Demandas_FKIndex1(Pedido_idPedido)
);

CREATE TABLE Funcionario (
  idFuncionario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Setor_idSetor INTEGER UNSIGNED NOT NULL,
  Nome INTEGER UNSIGNED NOT NULL,
  idSetor INTEGER UNSIGNED NOT NULL,
  Telefone INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idFuncionario),
  INDEX Funcionario_FKIndex1(Setor_idSetor)
);

CREATE TABLE Pedido (
  idPedido INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Usuario_idUsuario INTEGER UNSIGNED NOT NULL,
  CPF INTEGER UNSIGNED NOT NULL,
  DataCadastro INTEGER UNSIGNED NOT NULL,
  DataInicio DATETIME NOT NULL,
  DataFim DATETIME NOT NULL,
  StatusPedido INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idPedido),
  INDEX Pedido_FKIndex1(Usuario_idUsuario)
);

CREATE TABLE Setor (
  idSetor INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TipoDemanda_idTipoDemanda INTEGER UNSIGNED NOT NULL,
  Nome VARCHAR(20) NOT NULL,
  Secretaria VARCHAR(20) NOT NULL,
  PRIMARY KEY(idSetor),
  INDEX Setor_FKIndex1(TipoDemanda_idTipoDemanda)
);

CREATE TABLE TipoDemanda (
  idTipoDemanda INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Demandas_idDemandas INTEGER UNSIGNED NOT NULL,
  Descricao INTEGER UNSIGNED NOT NULL,
  IdSetor INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idTipoDemanda),
  INDEX TipoDemanda_FKIndex1(Demandas_idDemandas)
);

CREATE TABLE Usuario (
  idUsuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CPF INTEGER UNSIGNED NOT NULL,
  Nome VARCHAR(20) NOT NULL,
  DataNascimento INTEGER UNSIGNED NOT NULL,
  CEP INTEGER UNSIGNED NOT NULL,
  Logradouro INTEGER UNSIGNED NOT NULL,
  Numero INTEGER UNSIGNED NOT NULL,
  Complemento INTEGER UNSIGNED NOT NULL,
  Bairro VARCHAR(20) NOT NULL,
  Telefone INTEGER UNSIGNED NOT NULL,
  Email INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idUsuario)
);


